import { CamposM2M, CamposM2O, CamposSimples, Obra } from './tipos';

export const camposPlanos: (keyof CamposSimples)[] = [
  'registro',
  'titulo',
  'sintesis',
  'comentario_bibliografico',
  'iconotexto',
];

export const camposM2O: [relacion: string, nuevaLLave?: keyof CamposM2O][] = [
  ['fuente.descripcion', 'fuente'],
  ['imagen.id', 'imagen'],
  ['categoria1.nombre', 'categoria1'],
  ['categoria2.nombre', 'categoria2'],
  ['categoria3.nombre', 'categoria3'],
  ['categoria4.nombre', 'categoria4'],
  ['categoria5.nombre', 'categoria5'],
  ['categoria6.nombre', 'categoria6'],
  ['donante.nombre', 'donante'],
  ['ciudad_origen.nombre', 'ciudad_origen'],
  ['ubicacion.nombre', 'ubicacion'],
  ['ubicacion.ciudad.nombre', 'ciudad'],
  ['ubicacion.ciudad.pais.nombre', 'pais'],
  ['relato_visual.nombre', 'relato_visual'],
  ['tipo_gestual.nombre', 'tipo_gestual'],
  ['complejo_gestual.nombre', 'complejo_gestual'],
  ['fisiognomica.nombre', 'fisiognomica'],
  ['fisiognomica_imagen.nombre', 'fisiognomica_imagen'],
  ['rostro.nombre', 'rostro'],
  ['gesto1.nombre', 'gesto1'],
  ['gesto1.codigo'],
  ['gesto2.nombre', 'gesto2'],
  ['gesto2.codigo'],
  ['gesto3.nombre', 'gesto3'],
  ['gesto3.codigo'],
];

export const camposM2M: [coleccion: keyof Obra, llave: 'nombre' | 'apellido', nuevaLlave?: keyof CamposM2M][] = [
  ['autores', 'nombre', 'autores'],
  ['autores', 'apellido'],
  ['escenarios', 'nombre', 'escenarios'],
  ['objetos', 'nombre', 'objetos'],
  ['tecnicas', 'nombre', 'tecnicas'],
  ['personajes', 'nombre', 'personajes'],
  ['simbolos', 'nombre', 'simbolos'],
  ['descriptores', 'nombre', 'descriptores'],
  ['caracteristicas', 'nombre', 'caracteristicas'],
];

export const colecciones = [
  'obras',
  'autores',
  'personajes',
  'fuentes',
  'ubicaciones',
  'ciudades',
  'paises',
  'categorias1',
  'categorias2',
  'categorias3',
  'categorias4',
  'categorias5',
  'categorias6',
  'objetos',
  'escenarios',
  'tecnicas',
  'donantes',
  'relatos_visuales',
  'complejos_gestuales',
  'tipos_gestuales',
  'gestos',
  'fisiognomicas',
  'fisiognomicas_imagen',
  'cartelas_filacterias',
  'rostros',
  'simbolos',
  'descriptores',
  'caracteristicas',
];

/**
 * Mapa de relaciones para encontrar obras afectadas por cambios en colecciones relacionadas.
 * M2O: campo directo en la tabla obras
 * M2M: nombre de la tabla pivote que conecta obras con la colección
 */
export const mapaRelaciones: Record<string, { tipo: 'M2O' | 'M2M'; campo?: string; tablaPivote?: string }> = {
  fuentes: { tipo: 'M2O', campo: 'fuente' },
  categorias1: { tipo: 'M2O', campo: 'categoria1' },
  categorias2: { tipo: 'M2O', campo: 'categoria2' },
  categorias3: { tipo: 'M2O', campo: 'categoria3' },
  categorias4: { tipo: 'M2O', campo: 'categoria4' },
  categorias5: { tipo: 'M2O', campo: 'categoria5' },
  categorias6: { tipo: 'M2O', campo: 'categoria6' },
  donantes: { tipo: 'M2O', campo: 'donante' },
  ubicaciones: { tipo: 'M2O', campo: 'ubicacion' },
  ciudades: { tipo: 'M2O', campo: 'ciudad' },
  paises: { tipo: 'M2O', campo: 'pais' },
  relatos_visuales: { tipo: 'M2O', campo: 'relato_visual' },
  complejos_gestuales: { tipo: 'M2O', campo: 'complejo_gestual' },
  tipos_gestuales: { tipo: 'M2O', campo: 'tipo_gestual' },
  gestos: { tipo: 'M2O', campo: 'gesto1' }, // Simplificado: también afecta gesto2, gesto3
  fisiognomicas: { tipo: 'M2O', campo: 'fisiognomica' },
  fisiognomicas_imagen: { tipo: 'M2O', campo: 'fisiognomica_imagen' },
  rostros: { tipo: 'M2O', campo: 'rostro' },
  ciudad_origen: { tipo: 'M2O', campo: 'ciudad_origen' },
  autores: { tipo: 'M2M', tablaPivote: 'obras_autores' },
  personajes: { tipo: 'M2M', tablaPivote: 'obras_personajes' },
  objetos: { tipo: 'M2M', tablaPivote: 'obras_objetos' },
  escenarios: { tipo: 'M2M', tablaPivote: 'obras_escenarios' },
  tecnicas: { tipo: 'M2M', tablaPivote: 'obras_tecnicas' },
  simbolos: { tipo: 'M2M', tablaPivote: 'obras_simbolos' },
  descriptores: { tipo: 'M2M', tablaPivote: 'obras_descriptores' },
  caracteristicas: { tipo: 'M2M', tablaPivote: 'obras_caracteristicas' },
};
