version: '3.9'

services:
  # ----- CONTENEDOR PARA BASE DE DATOS -----
  bd:
    container_name: arca-cms-bd
    image: postgis/postgis:13-master
    restart: unless-stopped
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./datos:/var/lib/postgresql/data
    networks:
      - arca-cms-red
    environment:
      POSTGRES_USER: ${BD_USUARIO}
      POSTGRES_PASSWORD: ${BD_CLAVE}
      POSTGRES_DB: ${BD_NOMBRE_BD}

  # ----- CONTENEDOR PARA SISTEMA CACHE -----
  cache:
    container_name: arca-cms-cache
    image: redis:6
    restart: unless-stopped
    networks:
      - arca-cms-red

  # ----- CONTENEDOR PARA CMS -----
  directus:
    container_name: arca-cms
    image: directus/directus
    restart: unless-stopped
    ports:
      - ${CMS_PUERTO}:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    networks:
      - arca-cms-red
    depends_on:
      - cache
      - bd
    environment:
      PUBLIC_URL: ${CMS_URL}
      KEY: ${CMS_LLAVE}
      SECRET: ${CMS_SECRETO}
      CORS_ENABLED: 'true'
      CORS_ORIGIN: 'true'

      LOG_LEVEL: 'error'

      DB_CLIENT: 'pg'
      DB_HOST: 'arca-cms-bd'
      DB_PORT: '5432'

      DB_DATABASE: ${BD_NOMBRE_BD}
      DB_USER: ${BD_USUARIO}
      DB_PASSWORD: ${BD_CLAVE}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${CMS_EMAIL}
      ADMIN_PASSWORD: ${CMS_CLAVE}

      EMAIL_FROM: ${EMAIL_CORREO}
      EMAIL_TRANSPORT: ${EMAIL_TIPO}
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_PROVEEDOR}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PUERTO}
      EMAIL_SMTP_USER: ${EMAIL_SMTP_USUARIO}
      EMAIL_SMTP_PASSWORD: ${EMAIL_SMTP_CLAVE}

      ASSETS_TRANSFORM_IMAGE_MAX_DIMENSION: '9000'
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_BD_URL: 'arca-bdbuscador'

  # ----- CONTENEDOR PARA CMS -----
  buscador:
    container_name: arca-bdbuscador
    image: getmeili/meilisearch:v1.0
    restart: unless-stopped
    volumes:
      - ./datos-buscador:/meili_data
    networks:
      - arca-cms-red
    depends_on:
      - bd
      - directus
    ports:
      - ${MEILI_PUERTO}:7700
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: 'production'
      MEILI_NO_ANALYTICS: true

networks:
  arca-cms-red:
